# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Harve\OneDrive\Documents\GitHub\UI-Design-Mockups\Release\App.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from PyQt5.QtGui import QIcon
import UI_Mockup as UI

filename = ""
device = ""
deviceColour = ""
size = ""

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 623)
        MainWindow.setFixedSize(675,623)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/Logo.PNG"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGenerate.setEnabled(False)
        self.buttonGenerate.setGeometry(QtCore.QRect(50, 530, 559, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.buttonGenerate.setFont(font)
        self.buttonGenerate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonGenerate.setAutoFillBackground(False)
        self.buttonGenerate.setObjectName("buttonGenerate")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-4, 30, 671, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 23, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 252, 252))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 23, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 23, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(54, 23, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 671, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 104, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 6, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 104, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 6, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(151, 104, 209))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 6, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(37, 6, 76))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 160, 151, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 240, 151, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAutoFillBackground(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 320, 181, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_4.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAutoFillBackground(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 400, 161, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.label_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(True)
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(57, 480, 551, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.radioPhone = QtWidgets.QRadioButton(self.centralwidget)
        self.radioPhone.setGeometry(QtCore.QRect(250, 250, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioPhone.setFont(font)
        self.radioPhone.setAutoExclusive(False)
        self.radioPhone.setObjectName("radioPhone")
        self.radioTablet = QtWidgets.QRadioButton(self.centralwidget)
        self.radioTablet.setGeometry(QtCore.QRect(340, 250, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioTablet.setFont(font)
        self.radioTablet.setAutoExclusive(False)
        self.radioTablet.setObjectName("radioTablet")
        self.radioLaptop = QtWidgets.QRadioButton(self.centralwidget)
        self.radioLaptop.setGeometry(QtCore.QRect(430, 250, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioLaptop.setFont(font)
        self.radioLaptop.setAutoExclusive(False)
        self.radioLaptop.setObjectName("radioLaptop")
        self.radioMonitor = QtWidgets.QRadioButton(self.centralwidget)
        self.radioMonitor.setGeometry(QtCore.QRect(520, 250, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioMonitor.setFont(font)
        self.radioMonitor.setAutoExclusive(False)
        self.radioMonitor.setObjectName("radioMonitor")
        self.radioColourWhite = QtWidgets.QRadioButton(self.centralwidget)
        self.radioColourWhite.setGeometry(QtCore.QRect(250, 330, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioColourWhite.setFont(font)
        self.radioColourWhite.setAutoExclusive(False)
        self.radioColourWhite.setObjectName("radioColourWhite")
        self.radioColourBlack = QtWidgets.QRadioButton(self.centralwidget)
        self.radioColourBlack.setGeometry(QtCore.QRect(340, 330, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioColourBlack.setFont(font)
        self.radioColourBlack.setAutoExclusive(False)
        self.radioColourBlack.setObjectName("radioColourBlack")
        self.radioSizeLarge = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSizeLarge.setGeometry(QtCore.QRect(340, 410, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioSizeLarge.setFont(font)
        self.radioSizeLarge.setAutoExclusive(False)
        self.radioSizeLarge.setObjectName("radioSizeLarge")
        self.radioSizeSmall = QtWidgets.QRadioButton(self.centralwidget)
        self.radioSizeSmall.setGeometry(QtCore.QRect(250, 410, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.radioSizeSmall.setFont(font)
        self.radioSizeSmall.setAutoExclusive(False)
        self.radioSizeSmall.setObjectName("radioSizeSmall")
        self.buttonUpload = QtWidgets.QPushButton(self.centralwidget)
        self.buttonUpload.setEnabled(True)
        self.buttonUpload.setGeometry(QtCore.QRect(250, 180, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.buttonUpload.setFont(font)
        self.buttonUpload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonUpload.setAutoFillBackground(False)
        self.buttonUpload.setCheckable(False)
        self.buttonUpload.setObjectName("buttonUpload")
        self.buttonManual = QtWidgets.QPushButton(self.centralwidget)
        self.buttonManual.setEnabled(True)
        self.buttonManual.setGeometry(QtCore.QRect(-10, 120, 681, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Emoji")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.buttonManual.setFont(font)
        self.buttonManual.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonManual.setAutoFillBackground(False)
        self.buttonManual.setObjectName("buttonManual")
        self.frame.raise_()
        self.buttonGenerate.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.progressBar.raise_()
        self.radioPhone.raise_()
        self.radioTablet.raise_()
        self.radioLaptop.raise_()
        self.radioMonitor.raise_()
        self.radioColourWhite.raise_()
        self.radioColourBlack.raise_()
        self.radioSizeLarge.raise_()
        self.radioSizeSmall.raise_()
        self.buttonUpload.raise_()
        self.buttonManual.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.buttonGenerate.clicked.connect(self.GenerateMockup)
        
        self.radioPhone.clicked.connect(self.DeviceCheck)
        self.radioTablet.clicked.connect(self.DeviceCheck)
        self.radioLaptop.clicked.connect(self.DeviceCheck)
        self.radioMonitor.clicked.connect(self.DeviceCheck)
        
        self.radioColourWhite.clicked.connect(self.DeviceColour)
        self.radioColourBlack.clicked.connect(self.DeviceColour)

        self.radioSizeSmall.clicked.connect(self.DeviceSize)
        self.radioSizeLarge.clicked.connect(self.DeviceSize)

        
        self.buttonUpload.clicked.connect(self.setImage)

        self.radioColourBlack.setEnabled(False)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mockup Generator"))
        self.buttonGenerate.setText(_translate("MainWindow", "Generate"))
        self.label.setText(_translate("MainWindow", "Mockup Generator"))
        self.label_2.setText(_translate("MainWindow", "Image"))
        self.label_3.setText(_translate("MainWindow", "Device"))
        self.label_4.setText(_translate("MainWindow", "Device Colour"))
        self.label_5.setText(_translate("MainWindow", "Device Size"))
        self.radioPhone.setText(_translate("MainWindow", "Phone"))
        self.radioTablet.setText(_translate("MainWindow", "Tablet"))
        self.radioLaptop.setText(_translate("MainWindow", "Laptop"))
        self.radioMonitor.setText(_translate("MainWindow", "Monitor"))
        self.radioColourWhite.setText(_translate("MainWindow", "White"))
        self.radioColourBlack.setText(_translate("MainWindow", "Black"))
        self.radioSizeLarge.setText(_translate("MainWindow", "Large"))
        self.radioSizeSmall.setText(_translate("MainWindow", "Small"))
        self.buttonUpload.setText(_translate("MainWindow", "Choose a file..."))
        self.buttonManual.setText(_translate("MainWindow", "User Manual "))

    
    def setImage(self):
        fileName, _ = QtWidgets.QFileDialog.getOpenFileName(None,"Select Image", "" ,"Image Files(*.png)")
        if fileName:
            pgValue = self.progressBar.value()
            pgValue+= 25
            self.buttonUpload.setEnabled(False)
            self.progressBar.setProperty("value", pgValue)
            global filename
            filename = fileName
        self.ActivateButton()
     
            #from PyQt5.QtWidgets import QFileDialog

    def DeviceCheck(self):
        pgValue = self.progressBar.value()
        global device
        if(self.radioPhone.isChecked()==True):
           self.radioTablet.setEnabled(False)
           self.radioLaptop.setEnabled(False)
           self.radioMonitor.setEnabled(False)
           pgValue+= 25
           device = "iPhone"
           self.progressBar.setProperty("value", pgValue)
        elif(self.radioTablet.isChecked()==True):
           self.radioPhone.setEnabled(False)
           self.radioLaptop.setEnabled(False)
           self.radioMonitor.setEnabled(False)
           pgValue+= 25
           device = "iPad"
           self.progressBar.setProperty("value", pgValue)
        elif(self.radioLaptop.isChecked()==True):
           self.radioTablet.setEnabled(False)
           self.radioPhone.setEnabled(False)
           self.radioMonitor.setEnabled(False)
           pgValue+= 25
           device = "Mac"
           self.progressBar.setProperty("value", pgValue)
        elif(self.radioMonitor.isChecked()==True):
           self.radioPhone.setEnabled(False)
           self.radioLaptop.setEnabled(False)
           self.radioTablet.setEnabled(False)
           pgValue+= 25
           device = "Monitor"
           self.progressBar.setProperty("value", pgValue)
        else:
            pgValue += -25
            self.radioPhone.setEnabled(True)
            self.radioLaptop.setEnabled(True)
            self.radioTablet.setEnabled(True)
            self.radioMonitor.setEnabled(True)
            self.progressBar.setProperty("value", pgValue)
        self.ActivateButton()
           

    def DeviceColour(self):
        global deviceColour
        pgValue = self.progressBar.value()
        if(self.radioColourWhite.isChecked()==True):
            pgValue += 25
            self.radioColourBlack.setEnabled(False)
            deviceColour = "White"
            self.progressBar.setProperty("value", pgValue)
        elif(self.radioColourBlack.isChecked()==True):
            pgValue += 25
            self.radioColourWhite.setEnabled(False)
            deviceColour = "Black"
            self.progressBar.setProperty("value", pgValue)
        else:
            pgValue += -25
            self.radioColourBlack.setEnabled(True)
            self.radioColourWhite.setEnabled(True)
            self.progressBar.setProperty("value", pgValue)
        self.ActivateButton()


    def DeviceSize(self):
        global size
        pgValue = self.progressBar.value()
        if(self.radioSizeSmall.isChecked()==True):
            pgValue += 25
            self.radioSizeLarge.setEnabled(False)
            size = "small"
            self.progressBar.setProperty("value", pgValue)
        elif(self.radioSizeLarge.isChecked()==True):
            pgValue += 25
            self.radioSizeSmall.setEnabled(False)
            size = "large"
            self.progressBar.setProperty("value", pgValue)
        else:
            pgValue += -25
            self.radioSizeSmall.setEnabled(True)
            self.radioSizeLarge.setEnabled(True)
            self.progressBar.setProperty("value", pgValue)
        self.ActivateButton()
        
    def ActivateButton(self):
        Value = self.progressBar.value()
        if(Value == 100):
            self.buttonGenerate.setEnabled(True)
            print("Ready")

    def resetWindow(self):
        self.progressBar.setProperty("value", 0)
        self.radioPhone.setEnabled(True)
        self.radioTablet.setEnabled(True)
        self.radioLaptop.setEnabled(True)
        self.radioMonitor.setEnabled(True)
        self.radioPhone.setChecked(False)
        self.radioTablet.setChecked(False)
        self.radioLaptop.setChecked(False)
        self.radioMonitor.setChecked(False)
        
        self.buttonUpload.setEnabled(True)
        
        self.radioColourBlack.setEnabled(False)
        self.radioColourWhite.setEnabled(True)
        
        self.radioColourWhite.setChecked(False)
        self.radioColourBlack.setChecked(False)

        self.buttonGenerate.setEnabled(False)
        
        self.radioSizeSmall.setEnabled(True)
        self.radioSizeLarge.setEnabled(True)
        
        self.radioSizeSmall.setChecked(False)
        self.radioSizeLarge.setChecked(False)
        
    def GenerateMockup(self):
        print("Image = "+ filename)
        UI.CreateMockup(filename,deviceColour,size,device)
        print("Success")
        self.resetWindow()

    

            
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

